/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const APIException = require('./APIException');

/**
 * Creates an instance of ErrorException
 */
class ErrorException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.ns = null;

        /**
         * TODO: Write general description for this field
         */
        this.errorCode = null;

        /**
         * TODO: Write general description for this field
         */
        this.errorMessage = null;

        /**
         * TODO: Write general description for this field
         */
        this.errorAuxiliary = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'ns', realName: 'ns' },
            { name: 'errorCode', realName: 'error-code' },
            { name: 'errorMessage', realName: 'error-message' },
            { name: 'errorAuxiliary', realName: 'error-auxiliary' },
        ]);
    }
}

module.exports = ErrorException;
