/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const APIException = require('./APIException');

/**
 * Creates an instance of M100InventoryDatacenters401ErrorException
 */
class M100InventoryDatacenters401ErrorException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.error = null;

        /**
         * TODO: Write general description for this field
         */
        this.errorCode = null;

        /**
         * TODO: Write general description for this field
         */
        this.errorDescription = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'error', realName: 'error' },
            { name: 'errorCode', realName: 'error-code' },
            { name: 'errorDescription', realName: 'error_description' },
        ]);
    }
}

module.exports = M100InventoryDatacenters401ErrorException;
