/*
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.AuthenticationController;
const M100AuthValidatetokenResponse = testerlib.M100AuthValidatetokenResponse;
const M100AuthGeneratetokenResponse = testerlib.M100AuthGeneratetokenResponse;

describe("AuthenticationController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Validate the authentication token and get information about the user (roles, permissions, etc.)
     */
    it("should testTestValidateAuthenticationToken1 response", function testTestValidateAuthenticationToken1Test(done) {
        controller.get100AuthValidatetokenGet(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
