/*
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.DatacentresController;
const M100InventoryDatacentersResponse = testerlib.M100InventoryDatacentersResponse;

describe("DatacentresController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Get list of all the data centers
     */
    it("should testTestGetListOfAllTheDataCenters1 response", function testTestGetListOfAllTheDataCenters1Test(done) {
        controller.get100InventoryDatacentersGet(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
