/*
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");
const baseController = require("../../lib/Controllers/BaseController");

const controller = testerlib.LinksController;
const M100InventoryLinksResponse = testerlib.M100InventoryLinksResponse;
const M100InventoryLinksHistoryResponse = testerlib.M100InventoryLinksHistoryResponse;
const Link = testerlib.Link;
const M100InventoryLinkResponse = testerlib.M100InventoryLinkResponse;
const M100InventoryLinkRequest = testerlib.M100InventoryLinkRequest;

describe("LinksController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Create Link and initial Contract
     */
    it("should testTestCreateLinkAndInitialContract1 response", function testTestCreateLinkAndInitialContract1Test(done) {
        // parameters for the API call
        let body = null;

        controller.create100InventoryLinkPost(body, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
