/*
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.VnfsController;
const M100MarketplaceImageResponse = testerlib.M100MarketplaceImageResponse;

describe("VnfsController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * List images in the Marketplace
     */
    it("should testTestListImagesInTheMarketplace1 response", function testTestListImagesInTheMarketplace1Test(done) {
        controller.get100MarketplaceImageGet(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

});
