/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Contract
 */
class Contract extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.contractid = this.constructor.getValue(obj.contractid);
        this.duration = this.constructor.getValue(obj.duration);
        this.bandwidth = this.constructor.getValue(obj.bandwidth);
        this.price = this.constructor.getValue(obj.price);
        this.contractStatus = this.constructor.getValue(obj.contractStatus);
        this.version = this.constructor.getValue(obj.version);
        this.deletedtimestamp = this.constructor.getValue(obj.deletedtimestamp);
        this.currencyCode = this.constructor.getValue(obj.currencyCode);
        this.currencyID = this.constructor.getValue(obj.currencyID);
        this.renewalOption = this.constructor.getValue(obj.renewalOption || obj['renewal-option']);
        this.contractStartTime =
          this.constructor.getValue(obj.contractStartTime
     || obj['contract-start-time']);
        this.contractEndTime =
          this.constructor.getValue(obj.contractEndTime
     || obj['contract-end-time']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'contractid', realName: 'contractid' },
            { name: 'duration', realName: 'duration' },
            { name: 'bandwidth', realName: 'bandwidth' },
            { name: 'price', realName: 'price' },
            { name: 'contractStatus', realName: 'contractStatus' },
            { name: 'version', realName: 'version' },
            { name: 'deletedtimestamp', realName: 'deletedtimestamp' },
            { name: 'currencyCode', realName: 'currencyCode' },
            { name: 'currencyID', realName: 'currencyID' },
            { name: 'renewalOption', realName: 'renewal-option' },
            { name: 'contractStartTime', realName: 'contract-start-time' },
            { name: 'contractEndTime', realName: 'contract-end-time' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Contract;
