/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100InventoryLinksResponse
 */
class M100InventoryLinksResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.description = this.constructor.getValue(obj.description);
        this.latency = this.constructor.getValue(obj.latency);
        this.linkid = this.constructor.getValue(obj.linkid);
        this.contracts = this.constructor.getValue(obj.contracts);
        this.tag = this.constructor.getValue(obj.tag);
        this.connections = this.constructor.getValue(obj.connections);
        this.type = this.constructor.getValue(obj.type);
        this.linkStatus = this.constructor.getValue(obj.linkStatus);
        this.topologyTagUuid =
          this.constructor.getValue(obj.topologyTagUuid
     || obj.topology_tag_uuid);
        this.billingId = this.constructor.getValue(obj.billingId || obj['billing-id']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'description', realName: 'description' },
            { name: 'latency', realName: 'latency' },
            { name: 'linkid', realName: 'linkid' },
            { name: 'contracts', realName: 'contracts', array: true, type: 'Contract' },
            { name: 'tag', realName: 'tag' },
            { name: 'connections', realName: 'connections', array: true },
            { name: 'type', realName: 'type' },
            { name: 'linkStatus', realName: 'linkStatus' },
            { name: 'topologyTagUuid', realName: 'topology_tag_uuid' },
            { name: 'billingId', realName: 'billing-id' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100InventoryLinksResponse;
