/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100AuthValidatetokenResponse
 */
class M100AuthValidatetokenResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.companyName = this.constructor.getValue(obj.companyName || obj['company-name']);
        this.userid = this.constructor.getValue(obj.userid);
        this.internalid = this.constructor.getValue(obj.internalid);
        this.customerid = this.constructor.getValue(obj.customerid);
        this.customerAccount =
          this.constructor.getValue(obj.customerAccount
     || obj['customer-account']);
        this.billings = this.constructor.getValue(obj.billings);
        this.roles = this.constructor.getValue(obj.roles);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'companyName', realName: 'company-name' },
            { name: 'userid', realName: 'userid' },
            { name: 'internalid', realName: 'internalid' },
            { name: 'customerid', realName: 'customerid' },
            { name: 'customerAccount', realName: 'customer-account' },
            { name: 'billings', realName: 'billings', array: true, type: 'Billing' },
            { name: 'roles', realName: 'roles', array: true, type: 'Role' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100AuthValidatetokenResponse;
