/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100InventoryLinkResponse
 */
class M100InventoryLinkResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.successAuxiliary =
          this.constructor.getValue(obj.successAuxiliary
     || obj['success-auxiliary']);
        this.successCode = this.constructor.getValue(obj.successCode || obj['success-code']);
        this.successMessage =
          this.constructor.getValue(obj.successMessage
     || obj['success-message']);
        this.params = this.constructor.getValue(obj.params);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'successAuxiliary', realName: 'success-auxiliary' },
            { name: 'successCode', realName: 'success-code' },
            { name: 'successMessage', realName: 'success-message' },
            { name: 'params', realName: 'params', type: 'Params' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100InventoryLinkResponse;
