/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100InventoryVnfVportRequest
 */
class M100InventoryVnfVportRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.customeruuid = this.constructor.getValue(obj.customeruuid);
        this.vnfuuid = this.constructor.getValue(obj.vnfuuid);
        this.managementPort = this.constructor.getValue(obj.managementPort || obj.management_port);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'customeruuid', realName: 'customeruuid' },
            { name: 'vnfuuid', realName: 'vnfuuid' },
            { name: 'managementPort', realName: 'management_port' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100InventoryVnfVportRequest;
