/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100InventoryDatacentersResponse
 */
class M100InventoryDatacentersResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cityname = this.constructor.getValue(obj.cityname);
        this.countryname = this.constructor.getValue(obj.countryname);
        this.datacentername = this.constructor.getValue(obj.datacentername);
        this.datacentercode = this.constructor.getValue(obj.datacentercode);
        this.datacenteruuid = this.constructor.getValue(obj.datacenteruuid);
        this.interfacetypes = this.constructor.getValue(obj.interfacetypes);
        this.operatorname = this.constructor.getValue(obj.operatorname);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cityname', realName: 'cityname' },
            { name: 'countryname', realName: 'countryname' },
            { name: 'datacentername', realName: 'datacentername' },
            { name: 'datacentercode', realName: 'datacentercode' },
            { name: 'datacenteruuid', realName: 'datacenteruuid' },
            { name: 'interfacetypes', realName: 'interfacetypes', array: true },
            { name: 'operatorname', realName: 'operatorname' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100InventoryDatacentersResponse;
