/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of M100InventoryLinksContractRequest37
 */
class M100InventoryLinksContractRequest37 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.duration = this.constructor.getValue(obj.duration);
        this.bandwidth = this.constructor.getValue(obj.bandwidth);
        this.renewalOption = this.constructor.getValue(obj.renewalOption || obj['renewal-option']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'duration', realName: 'duration' },
            { name: 'bandwidth', realName: 'bandwidth' },
            { name: 'renewalOption', realName: 'renewal-option' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = M100InventoryLinksContractRequest37;
