/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Params31
 */
class Params31 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.description = this.constructor.getValue(obj.description);
        this.duration = this.constructor.getValue(obj.duration);
        this.bandwidth = this.constructor.getValue(obj.bandwidth);
        this.latency = this.constructor.getValue(obj.latency);
        this.linkid = this.constructor.getValue(obj.linkid);
        this.contractid = this.constructor.getValue(obj.contractid);
        this.price = this.constructor.getValue(obj.price);
        this.contractStatus = this.constructor.getValue(obj.contractStatus);
        this.version = this.constructor.getValue(obj.version);
        this.deletedtimestamp = this.constructor.getValue(obj.deletedtimestamp);
        this.tag = this.constructor.getValue(obj.tag);
        this.connection = this.constructor.getValue(obj.connection);
        this.type = this.constructor.getValue(obj.type);
        this.billingId = this.constructor.getValue(obj.billingId || obj['billing-id']);
        this.renewalOption = this.constructor.getValue(obj.renewalOption || obj['renewal-option']);
        this.contractStartTime =
          this.constructor.getValue(obj.contractStartTime
     || obj['contract-start-time']);
        this.contractEndTime =
          this.constructor.getValue(obj.contractEndTime
     || obj['contract-end-time']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'description', realName: 'description' },
            { name: 'duration', realName: 'duration' },
            { name: 'bandwidth', realName: 'bandwidth' },
            { name: 'latency', realName: 'latency' },
            { name: 'linkid', realName: 'linkid' },
            { name: 'contractid', realName: 'contractid' },
            { name: 'price', realName: 'price' },
            { name: 'contractStatus', realName: 'contractStatus' },
            { name: 'version', realName: 'version' },
            { name: 'deletedtimestamp', realName: 'deletedtimestamp' },
            { name: 'tag', realName: 'tag' },
            { name: 'connection', realName: 'connection', array: true },
            { name: 'type', realName: 'type' },
            { name: 'billingId', realName: 'billing-id' },
            { name: 'renewalOption', realName: 'renewal-option' },
            { name: 'contractStartTime', realName: 'contract-start-time' },
            { name: 'contractEndTime', realName: 'contract-end-time' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Params31;
