/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Topology
 */
class Topology extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.uuid = this.constructor.getValue(obj.uuid);
        this.name = this.constructor.getValue(obj.name);
        this.description = this.constructor.getValue(obj.description);
        this.status = this.constructor.getValue(obj.status);
        this.customerUuid = this.constructor.getValue(obj.customerUuid || obj.customer_uuid);
        this.nsdUuid = this.constructor.getValue(obj.nsdUuid || obj.nsd_uuid);
        this.guidTopologyId = this.constructor.getValue(obj.guidTopologyId || obj.guid_topology_id);
        this.createdBy = this.constructor.getValue(obj.createdBy || obj.created_by);
        this.creationDate = this.constructor.getValue(obj.creationDate || obj.creation_date);
        this.deletionDate = this.constructor.getValue(obj.deletionDate || obj.deletion_date);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'uuid', realName: 'uuid' },
            { name: 'name', realName: 'name' },
            { name: 'description', realName: 'description' },
            { name: 'status', realName: 'status' },
            { name: 'customerUuid', realName: 'customer_uuid' },
            { name: 'nsdUuid', realName: 'nsd_uuid' },
            { name: 'guidTopologyId', realName: 'guid_topology_id' },
            { name: 'createdBy', realName: 'created_by' },
            { name: 'creationDate', realName: 'creation_date' },
            { name: 'deletionDate', realName: 'deletion_date' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Topology;
