/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Ttms100TopologyTagObjectsResponse
 */
class Ttms100TopologyTagObjectsResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.endpoints = this.constructor.getValue(obj.endpoints);
        this.links = this.constructor.getValue(obj.links);
        this.sharedvports = this.constructor.getValue(obj.sharedvports);
        this.topologyTag = this.constructor.getValue(obj.topologyTag || obj.topology_tag);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'endpoints', realName: 'endpoints', array: true, type: 'Endpoint' },
            { name: 'links', realName: 'links', array: true, type: 'Link66' },
            { name: 'sharedvports', realName: 'sharedvports', array: true },
            { name: 'topologyTag', realName: 'topology_tag' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Ttms100TopologyTagObjectsResponse;
