/**
 * TelstraProgrammableNetworkAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Vport
 */
class Vport extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.status = this.constructor.getValue(obj.status);
        this.bandwidth = this.constructor.getValue(obj.bandwidth);
        this.interfacesequence = this.constructor.getValue(obj.interfacesequence);
        this.vporttype = this.constructor.getValue(obj.vporttype);
        this.vportuuid = this.constructor.getValue(obj.vportuuid);
        this.vportvalue = this.constructor.getValue(obj.vportvalue);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'status', realName: 'status' },
            { name: 'bandwidth', realName: 'bandwidth' },
            { name: 'interfacesequence', realName: 'interfacesequence' },
            { name: 'vporttype', realName: 'vporttype' },
            { name: 'vportuuid', realName: 'vportuuid' },
            { name: 'vportvalue', realName: 'vportvalue', type: 'Vportvalue' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Vport;
